modelname: blip2-coco-approach1_att_based
basemodel: blip2
_target_: src.model.blip2.blip2_cir_approach1_att_based.blip2_cir

ckpt_path: ${model.ckpt.path}

model:
  _target_: src.model.blip2.blip2_cir_approach1_att_based.BLIP2Cir
  vit_model: "eva_clip_g"
  image_size: ${model.ckpt.image_size}
  drop_path_rate: 0
  use_grad_checkpoint: True
  vit_precision: "fp32"
  train_vit: False
  num_query_token: 32
  vit: "large"

  loss: ${model.loss}

  si_ti_weight: ${model.loss_terms.si_ti_weight}
  si_tc_weight: ${model.loss_terms.si_tc_weight}