# @package _global_

defaults:
  - override /data: cirr.yaml
  - override /test: cirr.yaml
  - override /model: blip2-coco-approach1_penalty_loss.yaml
  - override /model/ckpt: blip2-l-coco.yaml
  - override /model/loss_terms: si_ti

machine:
  batch_size: 64

model:
  optimizer:
    lr: 1e-4
  weights_initialization: "not-image"

trainer:
  devices: 1
  max_epochs: 2
  save_ckpt: all
  test: cirr_approach1_penalty_loss


val: False
run_name: base